[package]
name = "debugger-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.26.2", features = ["process", "signal", "ptrace"] }
anyhow = "1.0.74"
libc = "0.2.155"
gimli = "0.31.1"
object = "0.36.7"
memmap2 = "0.9.5"
lazy_static = "1.5.0"
